# Generated by Django 4.2.27 on 2026-01-03 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('feels_like', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField(help_text='Humidity percentage')),
                ('pressure', models.IntegerField(help_text='Pressure in hPa')),
                ('wind_speed', models.FloatField(help_text='Wind speed in m/s')),
                ('wind_direction', models.IntegerField(blank=True, help_text='Wind direction in degrees', null=True)),
                ('visibility', models.IntegerField(blank=True, help_text='Visibility in meters', null=True)),
                ('cloudiness', models.IntegerField(default=0, help_text='Cloudiness percentage')),
                ('rain_volume', models.FloatField(blank=True, help_text='Rain volume in mm (last 3 hours)', null=True)),
                ('snow_volume', models.FloatField(blank=True, help_text='Snow volume in mm (last 3 hours)', null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['city', 'date'], name='weather_wea_city_3e2154_idx'), models.Index(fields=['timestamp'], name='weather_wea_timesta_7bce59_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('forecast_date', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('rain_probability', models.IntegerField(blank=True, help_text='Rain probability percentage', null=True)),
                ('stored_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['forecast_date'],
                'indexes': [models.Index(fields=['city', 'forecast_date'], name='weather_for_city_c12285_idx')],
            },
        ),
    ]
